import time
import pandas as pd
import os
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from seleniumbase import BaseCase, SB

class WebScraper(BaseCase):
    def wait_for_element(self, by, value, timeout=3):
        """Belirtilen öğeyi bekler."""
        try:
            element = WebDriverWait(self.driver, timeout).until(
                EC.presence_of_element_located((by, value))
            )
            return element
        except Exception as e:
            print(f"Hata: Element beklenirken timeout oluştu - {by}: {value}. Hata: {e}")
            return None

    def click_button(self, by, value, timeout=3):
        """Belirtilen butona tıklar."""
        element = self.wait_for_element(by, value, timeout)
        if element:
            try:
                element.click()
                print(f"Butona tıklama işlemi başarılı - {by}: {value}")
            except Exception as e:
                print(f"Hata: Butona tıklanamadı - {by}: {value}. Hata: {e}")
        else:
            print(f"Hata: Buton bulunamadı - {by}: {value}")

    def switch_to_iframe_and_click(self, by, value):
        """İframe içindeki belirtilen butona tıklar."""
        iframes = self.driver.find_elements(By.TAG_NAME, "iframe")
        print(f"Sayfada {len(iframes)} adet iframe bulundu.")
        for index, iframe in enumerate(iframes):
            try:
                self.driver.switch_to.frame(iframe)
                element = self.wait_for_element(by, value, timeout=3)
                if element:
                    self.click_button(by, value)
                    self.driver.switch_to.default_content()
                    return True
            except Exception as e:
                print(f"Hata: İframe içinde hata oluştu - {index}. Hata: {e}")
            self.driver.switch_to.default_content()
        print("Hata: İframe içinde buton bulunamadı veya tıklanamadı.")
        return False

    def collect_data_from_site(self, site, first_site):
        """Belirtilen siteden verileri toplar."""
        self.open(site)
        time.sleep(1)  # Sayfanın tamamen yüklenmesini bekleme

        # İlk site için çerez butonunu tıklamayı dene
        if first_site:
            if not self.switch_to_iframe_and_click(By.XPATH, "//*[@title='Çerezleri Kabul Et']"):
                self.click_button(By.XPATH, "//*[@title='Kabul Et']")

        time.sleep(1)  # Sayfanın yüklenmesini bekle
        basliklar = self.find_elements('h1')
        icerikler = self.find_elements('p')
        if not basliklar or not icerikler:
            print("Hata: Başlıklar veya içerikler bulunamadı.")
            return set()

        ilgili_icerik = ' '.join([p.text for p in icerikler if p.text])
        data = {(baslik.text, ilgili_icerik) for baslik in basliklar if baslik.text and ilgili_icerik}
        return data

    def save_data_to_json(self, data, file_path='dünya2(5).json'):
        """Toplanan verileri JSON dosyasına ekleme modunda kaydeder."""
        if not data:
            print("Hata: Kaydedilecek veri bulunamadı.")
            return

        existing_data = set()
        if os.path.exists(file_path) and os.path.getsize(file_path) > 0:
            try:
                existing_data = set(pd.read_json(file_path, orient='records', lines=True).apply(tuple, axis=1).tolist())
            except ValueError as e:
                print(f"Hata: JSON dosyası okunamadı - {file_path}. Hata: {e}")

        data.update(existing_data)
        df = pd.DataFrame(list(data), columns=['baslik', 'icerik'])
        df.to_json(file_path, orient='records', lines=True, force_ascii=False)
        print(f"Veriler JSON dosyasına eklendi: {file_path}")

    def test_scraper(self):
        """Scraper'ı test eder."""
        siteler = [
#             'https://www.bbc.com/turkce/articles/cqlln85j89yo',
# 'https://www.bbc.com/turkce/articles/ck7772prz20o',
# 'https://www.bbc.com/turkce/articles/c6ppyppyv7go',
# 'https://www.bbc.com/turkce/articles/c0jjkj3wdq2o',
# 'https://www.bbc.com/turkce/articles/c2eem5ej7lro',
# 'https://www.bbc.com/turkce/articles/cn0044lmpkpo',
# 'https://www.bbc.com/turkce/articles/cv22xv76rzvo',
# 'https://www.bbc.com/turkce/articles/c066l5pg0zpo',
# 'https://www.bbc.com/turkce/articles/cneek2eyypdo',
# 'https://www.bbc.com/turkce/articles/c199xl4ywezo',
# 'https://www.bbc.com/turkce/articles/cz99zpm7yjgo',
# 'https://www.bbc.com/turkce/articles/ckkkv5r3n70o',
# 'https://www.bbc.com/turkce/articles/c3ggqzjgx70o',
# 'https://www.bbc.com/turkce/articles/c511nerj7k7o',
# 'https://www.bbc.com/turkce/articles/c3gjp8zk55yo',
# 'https://www.bbc.com/turkce/articles/c1vv107geglo',
# 'https://www.bbc.com/turkce/articles/cw00l0e6wgxo',
# 'https://www.bbc.com/turkce/articles/cd1143xkw5go',
# 'https://www.bbc.com/turkce/articles/cyjjkdg3zwyo',
# 'https://www.bbc.com/turkce/articles/c511mmp010go',
# 'https://www.bbc.com/turkce/articles/cyxx77vdv14o',
# 'https://www.bbc.com/turkce/articles/cd119ljqww0o',
# 'https://www.bbc.com/turkce/articles/c3ggqplpqpwo',
# 'https://www.bbc.com/turkce/articles/c511m7prngeo',
# 'https://www.bbc.com/turkce/articles/c3ggynwlgy7o',
# 'https://www.bbc.com/turkce/articles/crgg94044pwo',
# 'https://www.bbc.com/turkce/articles/crggvxm7zezo',
# 'https://www.bbc.com/turkce/articles/c722yqyv51jo',
# 'https://www.bbc.com/turkce/articles/c0jjvgqepyjo',
# 'https://www.bbc.com/turkce/articles/clll74gmqdro',
# 'https://www.bbc.com/turkce/articles/cd11wqqz82qo',
# 'https://www.bbc.com/turkce/articles/c1eeyypwjjlo',
# 'https://www.bbc.com/turkce/articles/cp449qgpnz5o',
# 'https://www.bbc.com/turkce/articles/ceqqj0v4dj4o',
# 'https://www.bbc.com/turkce/articles/cxee3mv7zpyo',
# 'https://www.bbc.com/turkce/articles/ce55j638j1go',
# 'https://www.bbc.com/turkce/articles/cl44ek3xxlno',
# 'https://www.bbc.com/turkce/articles/cjmmpk92mylo',
# 'https://www.bbc.com/turkce/articles/c3gg3xg1nk1o',
# 'https://www.bbc.com/turkce/articles/czrrlle7ywzo',
# 'https://www.bbc.com/turkce/articles/c4nnjz1ld21o',
# 'https://www.bbc.com/turkce/articles/cjmmg121dj7o',
# 'https://www.bbc.com/turkce/articles/c10019y78g2o',
# 'https://www.bbc.com/turkce/articles/c8882npn0xdo',
# 'https://www.bbc.com/turkce/articles/cj55gqzpr17o',
# 'https://www.bbc.com/turkce/articles/c3gg094e2jwo',
# 'https://www.bbc.com/turkce/articles/czrr2ndm2pko',
# 'https://www.bbc.com/turkce/articles/cv22e94kgx9o',
# 'https://www.bbc.com/turkce/articles/cpww8glyv4xo',
# 'https://www.bbc.com/turkce/articles/c900jq2gg44o',
# 'https://www.bbc.com/turkce/articles/c8vvl2je68go',
# 'https://www.bbc.com/turkce/articles/cyrr5n6d711o',
# 'https://www.bbc.com/turkce/articles/cydd1ejzly3o',
# 'https://www.bbc.com/turkce/articles/c888myyxv5zo',
# 'https://www.bbc.com/turkce/articles/cn4464n416ro',
# 'https://www.bbc.com/turkce/articles/cw44dx9yyweo',
# 'https://www.bbc.com/turkce/articles/c288vmk9x00o',
# 'https://www.bbc.com/turkce/articles/clww7enpqd8o',
# 'https://www.bbc.com/turkce/articles/c6ppd89r481o',
# 'https://www.bbc.com/turkce/articles/cq5584n4v1ro',
# 'https://www.bbc.com/turkce/articles/ckvv1v227ljo',
# 'https://www.bbc.com/turkce/articles/cxee3mv7zpyo',
# 'https://www.bbc.com/turkce/articles/c1667pyw482o',
# 'https://www.bbc.com/turkce/articles/cmll8r1g0x3o',
# 'https://www.bbc.com/turkce/articles/cgll0n30ekko',
# 'https://www.bbc.com/turkce/articles/c1rr4ql734yo',
# 'https://www.bbc.com/turkce/articles/cjmmp3r2epno',
# 'https://www.bbc.com/turkce/articles/cgxxgpyp054o',
# 'https://www.bbc.com/turkce/articles/c4nnx78wq03o',
# 'https://www.bbc.com/turkce/articles/c1448y044j7o',
# 'https://www.bbc.com/turkce/articles/c3gg99y035ro',
# 'https://www.bbc.com/turkce/articles/cprrxd19qpro',
# 'https://www.bbc.com/turkce/articles/crggely6e8go',
# 'https://www.bbc.com/turkce/articles/c1448x7qpd2o',
# 'https://www.bbc.com/turkce/articles/c8771gmm3k1o',
# 'https://www.bbc.com/turkce/articles/cv22pp83y96o',
# 'https://www.bbc.com/turkce/articles/c999x7ge8q1o',
# 'https://www.bbc.com/turkce/articles/c8vvy9zzlgyo',
# 'https://www.bbc.com/turkce/articles/crgg4j386d4o',
# 'https://www.bbc.com/turkce/articles/cljj55393npo',
# 'https://www.bbc.com/turkce/articles/crggj7y8e5vo',
# 'https://www.bbc.com/turkce/articles/c511544y449o',
# 'https://www.bbc.com/turkce/articles/cv22619vny9o',
# 'https://www.bbc.com/turkce/articles/crggnv1gy44o',
# 'https://www.bbc.com/turkce/articles/cqvv7430d9go',
# 'https://www.bbc.com/turkce/articles/cm55x8lddelo',
# 'https://www.bbc.com/turkce/articles/c511xq07kxyo',
# 'https://www.bbc.com/turkce/articles/c877353vpemo',
# 'https://www.bbc.com/turkce/articles/cjllw1grnx8o',
# 'https://www.bbc.com/turkce/articles/c4nn0zgr5e9o',
# 'https://www.bbc.com/turkce/articles/c2eeg30p4mqo',
# 'https://www.bbc.com/turkce/articles/c4nn0ep674jo',
# 'https://www.bbc.com/turkce/articles/cx99r5k9dkvo',
# 'https://www.bbc.com/turkce/articles/c0xx54qxdwxo',
# 'https://www.bbc.com/turkce/articles/c0vv58jdwwwo',
# 'https://www.bbc.com/turkce/articles/cw448j5k80vo',
# 'https://www.bbc.com/turkce/articles/cm55j7xepmko',
# 'https://www.bbc.com/turkce/articles/c722nv440mmo',
# 'https://www.bbc.com/turkce/articles/c6ppz9dw2ewo',
# 'https://www.bbc.com/turkce/articles/cv22vdl1qg3o',
# 'https://www.bbc.com/turkce/articles/c3gg96yxvdgo',
# 'https://www.bbc.com/turkce/articles/c0dd4081340o',
# 'https://www.bbc.com/turkce/articles/c6ppl26ng7mo',
# 'https://www.bbc.com/turkce/articles/cv22795lre5o',
# 'https://www.bbc.com/turkce/articles/cz44rd582vpo',
# 'https://www.bbc.com/turkce/articles/c044mpvl87do',
# 'https://www.bbc.com/turkce/articles/cy77pqv8jdeo',
# 'https://www.bbc.com/turkce/articles/ceqq6w86xl2o',
# 'https://www.bbc.com/turkce/articles/c033k7y8xleo',
# 'https://www.bbc.com/turkce/articles/c4nn9jzxl6eo',
# 'https://www.bbc.com/turkce/articles/cy66526z7g4o',
# 'https://www.bbc.com/turkce/articles/c888724lw66o',
# 'https://www.bbc.com/turkce/articles/cyee43e1nd9o',
# 'https://www.bbc.com/turkce/articles/cd11zn9z4m7o',
# 'https://www.bbc.com/turkce/articles/c3ggvj9rj0jo',
# 'https://www.bbc.com/turkce/articles/clww98j2v9yo',
# 'https://www.bbc.com/turkce/articles/c5114jpe94ko',
# 'https://www.bbc.com/turkce/articles/cqee0yjp3gmo',
# 'https://www.bbc.com/turkce/articles/c1vv03kx50no',
# 'https://www.bbc.com/turkce/articles/cyxx93wn4v9o',
# 'https://www.bbc.com/turkce/articles/cyxvglg00dxo',
# 'https://www.bbc.com/turkce/articles/c0ddr9nr4kvo',
# 'https://www.bbc.com/turkce/articles/czqqgl5966po',
# 'https://www.bbc.com/turkce/articles/c977x0x04y2o',
# 'https://www.bbc.com/turkce/articles/cd113gv68g2o',
# 'https://www.bbc.com/turkce/articles/c4nnd5ye22ko',
# 'https://www.bbc.com/turkce/articles/clmmdr01dx1o',
# 'https://www.bbc.com/turkce/articles/crgg0739leeo',
# 'https://www.bbc.com/turkce/articles/crgg61p6n6no',
# 'https://www.bbc.com/turkce/articles/cjewxrrz88xo',
# 'https://www.bbc.com/turkce/articles/cn006g2ve87o',
# 'https://www.bbc.com/turkce/articles/ce5531v33n1o',
# 'https://www.bbc.com/turkce/articles/cqee8e0r999o',
# 'https://www.bbc.com/turkce/articles/cpdd4gg8x77o',
# 'https://www.bbc.com/turkce/articles/c6pp83w7j53o',
# 'https://www.bbc.com/turkce/articles/cv22pv08rddo',
# 'https://www.bbc.com/turkce/articles/ce44yzdllpgo',
# 'https://www.bbc.com/turkce/articles/cg33z2v9lmvo',
# 'https://www.bbc.com/turkce/articles/cgrr19z2en3o',
# 'https://www.bbc.com/turkce/articles/c1eek42q05no',
# 'https://www.bbc.com/turkce/articles/cn334lll2g9o',
# 'https://www.bbc.com/turkce/articles/cp99kl9kprxo',
# 'https://www.bbc.com/turkce/articles/crgg6007lzyo',
# 'https://www.bbc.com/turkce/articles/cx99787p4gyo',
# 'https://www.bbc.com/turkce/articles/clmm2vz0vmgo',
# 'https://www.bbc.com/turkce/articles/ckdd5le42n2o',
# 'https://www.bbc.com/turkce/articles/cg338wep1lgo',
# 'https://www.bbc.com/turkce/articles/ce44r07r7dro',
# 'https://www.bbc.com/turkce/articles/c2jjmyn4krdo',
# 'https://www.bbc.com/turkce/articles/cl5k3v2vyn9o',
# 'https://www.bbc.com/turkce/articles/c3gg7r3nky3o',
# 'https://www.bbc.com/turkce/articles/cw00glyrj42o',
# 'https://www.bbc.com/turkce/articles/c9rr4l1kyp4o',
# 'https://www.bbc.com/turkce/articles/c722z1jdywjo',
# 'https://www.bbc.com/turkce/articles/cv227jwedlxo',
# 'https://www.bbc.com/turkce/articles/cv227g2pkdzo',
# 'https://www.bbc.com/turkce/articles/c255jqn444wo',
# 'https://www.bbc.com/turkce/articles/c51144plxjro',
# 'https://www.bbc.com/turkce/articles/czrrn8g2w0ro',
# 'https://www.bbc.com/turkce/articles/cx77qv21vx7o',
# 'https://www.bbc.com/turkce/articles/c722w210gvjo',
# 'https://www.bbc.com/turkce/articles/c166xpe758ko',
# 'https://www.bbc.com/turkce/articles/cjmmn2vyl4ro',
# 'https://www.bbc.com/turkce/articles/clmmg4gm78po',
# 'https://www.bbc.com/turkce/articles/cn00yd1x9d5o',
# 'https://www.bbc.com/turkce/articles/cnkkjddvp5yo',
# 'https://www.bbc.com/turkce/articles/c6ppz7k000ko',
# 'https://www.bbc.com/turkce/articles/c3ggnz9g3ldo',
# 'https://www.bbc.com/turkce/articles/cp332mrzj8vo',
# 'https://www.bbc.com/turkce/articles/c133j048k7no',
# 'https://www.bbc.com/turkce/articles/cy99leg78j4o',
# 'https://www.bbc.com/turkce/articles/c3ggqw4541yo',
# 'https://www.bbc.com/turkce/articles/cn004le139go',
# 'https://www.bbc.com/turkce/articles/c03dlnjj3xgo',
# 'https://www.bbc.com/turkce/articles/cxrr6qv0klpo',
# 'https://www.bbc.com/turkce/articles/cjjj2dl1yljo',
# 'https://www.bbc.com/turkce/articles/c511vv91nnzo',
# 'https://www.bbc.com/turkce/articles/cv221633l1po',
# 'https://www.bbc.com/turkce/articles/c722zn76ze8o',
# 'https://www.bbc.com/turkce/articles/cl445273x76o',
# 'https://www.bbc.com/turkce/articles/cz9951zlxq1o',
# 'https://www.bbc.com/turkce/articles/cjqqv732wd9o',
# 'https://www.bbc.com/turkce/articles/c0jj07qwpqjo',
# 'https://www.bbc.com/turkce/articles/cpeey224d4go',
# 'https://www.bbc.com/turkce/articles/cd119z2kj0qo',
# 'https://www.bbc.com/turkce/articles/ce44j977ejxo',
# 'https://www.bbc.com/turkce/articles/ceqqlnj85dpo',
# 'https://www.bbc.com/turkce/articles/ckvv87539v2o',
# 'https://www.bbc.com/turkce/articles/c888px1zxyxo',
# 'https://www.bbc.com/turkce/articles/c3ggd40y55yo',
# 'https://www.bbc.com/turkce/articles/c4nnevyy385o',
# 'https://www.bbc.com/turkce/articles/cldd2l9r7dgo',
# 'https://www.bbc.com/turkce/articles/c6ppj8zzmqpo',
# 'https://www.bbc.com/turkce/articles/cv227lyrezgo',
# 'https://www.bbc.com/turkce/articles/cv22dy1ln7xo',
# 'https://www.bbc.com/turkce/articles/cnkkyege15zo',
# 'https://www.bbc.com/turkce/articles/c5115y96j55o',
# 'https://www.bbc.com/turkce/articles/c4nnwpp5xd0o',
# 'https://www.bbc.com/turkce/articles/cw005v104j9o',
# 'https://www.bbc.com/turkce/articles/cyrrd8xv4n3o',
# 'https://www.bbc.com/turkce/articles/c9rr7q0l40ko',
# 'https://www.bbc.com/turkce/articles/c9wwpkvzej3o',
# 'https://www.bbc.com/turkce/articles/c977elmd38vo',
# 'https://www.bbc.com/turkce/articles/cv22w3p3jjwo',
# 'https://www.bbc.com/turkce/articles/c3ggl32zv93o',
# 'https://www.bbc.com/turkce/articles/cneez97jkl1o',
# 'https://www.bbc.com/turkce/articles/cldd63ev4vqo',
# 'https://www.bbc.com/turkce/articles/cx774277lddo',
# 'https://www.bbc.com/turkce/articles/c3ggkneylrko',
# 'https://www.bbc.com/turkce/articles/clmm2ly9np5o',
# 'https://www.bbc.com/turkce/articles/c9xxdn46x5do',
# 'https://www.bbc.com/turkce/articles/c28872d78lno',
# 'https://www.bbc.com/turkce/articles/cv225gj8nwro',
# 'https://www.bbc.com/turkce/articles/c2lldyxg7n0o',
# 'https://www.bbc.com/turkce/articles/ckrr94gnlddo',
# 'https://www.bbc.com/turkce/articles/cxwwl3k8wvdo',
# 'https://www.bbc.com/turkce/articles/cw00e5ggl9eo',
# 'https://www.bbc.com/turkce/articles/c999kl4kzg1o',
# 'https://www.bbc.com/turkce/articles/cd116w9rdv3o',
# 'https://www.bbc.com/turkce/articles/c51ny2g0888o',
# 'https://www.bbc.com/turkce/articles/cd13xnlq0rxo',
# 'https://www.bbc.com/turkce/articles/ckr5g4kx332o',
# 'https://www.bbc.com/turkce/articles/cp3g8z18zd8o',
# 'https://www.bbc.com/turkce/articles/c1ej5z87q8lo',
# 'https://www.bbc.com/turkce/articles/cz4x7l0xj90o',
# 'https://www.bbc.com/turkce/articles/c0klk4ypzjro',
# 'https://www.bbc.com/turkce/articles/cw99jx8rw07o',
# 'https://www.bbc.com/turkce/articles/c1ww8l8657jo',
# 'https://www.bbc.com/turkce/articles/cqlnl8vxpnvo',
# 'https://www.bbc.com/turkce/articles/c6py26d34n6o',
# 'https://www.bbc.com/turkce/articles/cz74ee3zw8go',
# 'https://www.bbc.com/turkce/articles/cxxxgg7e4p4o',
# 'https://www.bbc.com/turkce/articles/c3ggnl60635o',
# 'https://www.bbc.com/turkce/articles/c3ggkpp9174o',
# 'https://www.bbc.com/turkce/articles/cn404lljy3mo',
# 'https://www.bbc.com/turkce/articles/cd115g4773lo',
# 'https://www.bbc.com/turkce/articles/c6ppr7gzp2vo',


# 'https://www.bbc.com/turkce/articles/c72p4xj90kdo',
# 'https://www.bbc.com/turkce/articles/ckdqd4qrjq0o'

'https://halktv.com.tr/dunya/en-zengin-aile-hizmetcileri-istismar-etti-845535h',
'https://halktv.com.tr/dunya/sahte-alkolden-olenlerin-sayisi-54e-yukseldi-845543h',
'https://halktv.com.tr/dunya/hindistanin-ankara-buyukelcisi-hayatini-kaybetti-845536h',
'https://halktv.com.tr/dunya/urdunun-baskenti-ammanda-bir-evde-siddetli-patlama-meydana-geldi-845503h',
'https://halktv.com.tr/dunya/rusya-ukrayna-elektrik-sebekesine-buyuk-bir-saldiri-baslatti-845561h'
# 'https://halktv.com.tr/dunya/rus-mahkemesinden-sok-karar-commerzbank-rusyadaki-varliklarini-devredecek-845420h',
# 'https://halktv.com.tr/dunya/26-katli-rezidansta-yangin-845631h',
# 'https://halktv.com.tr/dunya/dunyanin-takip-ettigi-davaya-kubada-dahil-oluyor-845655h',
# 'https://halktv.com.tr/dunya/zengin-aileye-emek-somurusu-sucundan-hapis-cezasi-845581h',
# 'https://halktv.com.tr/dunya/abdnin-arizona-eyaletinde-6-kisi-asiri-sicak-sebebiyle-oldu-845508h',
# 'https://halktv.com.tr/dunya/saldiri-sonrasi-zelenskyden-hava-savunma-talebi-845775h',
# 'https://halktv.com.tr/dunya/abdde-ikinci-el-konut-fiyatlari-tum-zamanlarin-en-yuksek-seviyesini-gordu-845492h',
# 'https://halktv.com.tr/dunya/hamas-gazze-seridinde-onlarca-insan-oldu-845664h',
# 'https://halktv.com.tr/dunya/iranin-tek-reformist-adayi-kadinlara-zorla-basortusu-taktiramayiz-845495h',
# 'https://halktv.com.tr/dunya/fettah-tamincenin-sahibi-oldugu-luks-rezidans-insaatinda-yangin-cikti-845899h',
# 'https://halktv.com.tr/dunya/icrc-saldirisi-abden-sivillerin-guvenligi-icin-acil-cagri-845822h',
# 'https://halktv.com.tr/dunya/yunanistanda-korkutan-covid-alarmi-vakalar-artiyor-845563h',
# 'https://halktv.com.tr/dunya/israil-durmuyor-saldirida-en-az-45-filistinli-olduruldu-845506h',
# 'https://halktv.com.tr/dunya/protesto-gosterilerini-organize-etmekle-suclanan-rapci-hakkinda-verilen-idam-845598h',
# 'https://halktv.com.tr/dunya/hamaneyden-adaylara-dusman-sevindirecek-sozler-soylemeyin-uyarisi-845573h',
# 'https://halktv.com.tr/dunya/yunanistanda-muhalefet-bbcnin-gocmen-olumleri-haberi-sonrasi-sorusturma-istedi-845683h',
# 'https://halktv.com.tr/dunya/sicaklik-46-dereceye-yukseldi-6-kisi-hayatini-kaybetti-845519h',
# 'https://halktv.com.tr/dunya/olen-hacilarin-sayisi-672ye-yukseldi-845888h',
# 'https://halktv.com.tr/dunya/israil-ordusu-yarali-filistinli-aracin-onune-kalkan-yapti-845668h',
# 'https://halktv.com.tr/dunya/selin-vurdugu-burundide-zorlu-kamp-hayati-845530h',
# 'https://halktv.com.tr/dunya/iddia-tel-aviv-yonetimi-yakin-zamanda-kassamin-yenilgisini-ilan-edecek-845491h',
# 'https://halktv.com.tr/dunya/hapishanelerde-yer-kalmadi-israil-filistinli-aktivistlerin-operasyonunu-iptal-etti-845870h',
# 'https://halktv.com.tr/dunya/netflix-patlamis-misir-satacak-845408h',
# 'https://halktv.com.tr/dunya/rusya-ukraynanin-fuzelerle-saldirdigini-iddia-etti-845897h',
# 'https://halktv.com.tr/dunya/fedden-4-bankaya-zayiflik-sinyali-845488h',
# 'https://halktv.com.tr/dunya/ticaret-bakani-cezayir-ve-tunusa-gidiyor-845528h',
# 'https://halktv.com.tr/dunya/husiler-abdye-ait-ucak-gemisini-vurduklarini-acikladi-845733h',
# 'https://halktv.com.tr/dunya/sosyal-medya-fenomeni-yasakli-plajda-yakayi-ele-verdi-845689h',
# 'https://halktv.com.tr/dunya/rusyadan-sonra-kazakistanda-da-metrolar-turistlerin-ilgi-odagi-oldu-845539h',
# 'https://halktv.com.tr/dunya/abd-husilerin-eisenhoweri-vurduk-aciklamasini-yalanladi-845804h',
# 'https://halktv.com.tr/dunya/justin-timberlake-zor-gunler-gecirdigini-soyledi-845625h',
# 'https://halktv.com.tr/dunya/israil-hizbullah-gerilimi-tirmaniyor-kuveyt-vatandaslarini-cagirdi-845550h',
# 'https://halktv.com.tr/dunya/tacikistanda-basortusu-yasaklandi-845409h',
# 'https://halktv.com.tr/dunya/fitch-gurcistanin-kredi-notu-gorunumunu-negatif-tuttu-845787h',
# 'https://halktv.com.tr/dunya/yattan-havai-fisek-attilar-ada-kul-oldu-845877h',
# 'https://halktv.com.tr/dunya/harry-potterin-yazari-isci-partisinin-translara-yonelik-soylemlerini-elestirdi-845642h',
# 'https://halktv.com.tr/dunya/gazzenin-savasla-yok-edilen-su-sistemi-cocuklari-hasta-ediyor-845393h',
# 'https://halktv.com.tr/dunya/manchester-havalimaninda-elektrikler-kesildi-ucuslarin-iptali-bekleniyor-845778h',
# 'https://halktv.com.tr/dunya/600u-askin-hacinin-olumuyle-ilgili-turizm-acentelerine-dava-acildi-845849h',
# 'https://halktv.com.tr/dunya/gazzeyi-yerle-bir-eden-israil-bunu-da-yapti-esir-aldiklari-filistinliyi-canli-845911h',
# 'https://halktv.com.tr/dunya/israil-yine-multeci-kampina-saldirdi-cok-sayida-olu-ve-yarali-var-845600h',
# 'https://halktv.com.tr/dunya/kizil-hac-gazzedeki-ofisinin-yakinindaki-saldirida-22-kisinin-oldugunu-acikladi-845540h',
# 'https://halktv.com.tr/dunya/hastanede-skandal-serumlari-musluk-suyu-ile-degistirdi-16-hasta-oldu-845676h',
# 'https://halktv.com.tr/dunya/guney-koreyi-tehdit-eden-dususte-ulusal-acil-durum-cagrisi-yapildi-844957h',
# 'https://halktv.com.tr/dunya/abd-netanyahu-bizi-hayal-kirikligina-ugratti-845292h',
# 'https://halktv.com.tr/dunya/kanada-iran-devrim-muhafizlarini-teror-orgutu-olarak-listeledi-844977h',
# 'https://halktv.com.tr/dunya/sahte-ickiden-29-kisi-oldu-844943h',
# 'https://halktv.com.tr/dunya/yeryuzunde-fesat-cikarmak-sucundan-4-kisiye-idam-cezasi-845123h',
# 'https://halktv.com.tr/dunya/her-yil-en-az-1-milyon-stajyer-kampanyasi-844721h',
# 'https://halktv.com.tr/dunya/netanyahunun-oglu-hava-kuvvetleri-komutanini-hedef-aldi-844770h',
# 'https://halktv.com.tr/dunya/fransada-asiri-sagin-yukselisi-ziyaretcileri-etkiler-mi-belediye-baskani-acikladi-844728h',
# 'https://halktv.com.tr/dunya/ukrayna-icin-bagis-yapti-vatana-ihanetten-yargilaniyor-844966h',
# 'https://halktv.com.tr/dunya/kuzey-kore-rusya-anlasmasi-guney-kore-buyukelciyi-cagirdi-845206h',
# 'https://halktv.com.tr/dunya/askeri-muhimmat-deposunda-patlama-9-olu-46-yarali-844814h',
# 'https://halktv.com.tr/dunya/zelenskiyden-romanyaya-tesekkur-845086h',
# 'https://halktv.com.tr/dunya/tum-maliyetleri-hesaba-katildiginda-dunyanin-yasamasi-en-pahali-10-sehri-845224h',
# 'https://halktv.com.tr/dunya/tehlike-daha-da-buyuyebilir-845112h',
# 'https://halktv.com.tr/dunya/iki-ulke-anlasti-anlasma-neyi-ongoruyor-844760h',
# 'https://halktv.com.tr/dunya/venedikin-126-yili-kaldi-su-altinda-kalabilir-845033h',
# 'https://halktv.com.tr/dunya/lubnandan-israile-fuze-saldirisi-845120h',
# 'https://halktv.com.tr/dunya/sinira-duvar-orulmus-uydu-goruntuleri-ortaya-cikti-845307h',
# 'https://halktv.com.tr/dunya/putin-o-ulkelere-rest-cekti-845170h',
# 'https://halktv.com.tr/dunya/isvicre-merkez-bankasi-faiz-indirimine-gitti-845074h',
# 'https://halktv.com.tr/dunya/orman-yanginlarinda-2-kisi-oldu-500-ev-kul-oldu-845104h',
# 'https://halktv.com.tr/dunya/sicak-havadan-155-kisi-oldu-hukumet-disari-cikmayin-uyarisi-yapti-845241h',
# 'https://halktv.com.tr/dunya/bir-ulke-daha-yasakladi-okullarda-cep-telefonu-yasaklaniyor-844836h',
# 'https://halktv.com.tr/dunya/dunyaca-unlu-universite-ifsa-oldu-844960h',
# 'https://halktv.com.tr/dunya/kurana-saygisizlik-iddiasiyla-kalabalik-tarafindan-yakilarak-katledildi-845315h',
# 'https://halktv.com.tr/dunya/olduresiye-dovuldum-demisti-mika-raun-yasadigi-saldirinin-sebebini-gozyaslari-844870h',
# 'https://halktv.com.tr/dunya/hacda-asiri-sicaklar-550den-fazla-can-aaldi-844874h',
# 'https://halktv.com.tr/dunya/almanyada-dhkp-c-uyesine-3-yil-hapis-cezasi-845138h',
# 'https://halktv.com.tr/dunya/issizlik-maasi-basvurulari-son-10-ayin-zirvesine-cikti-845103h',
# 'https://halktv.com.tr/dunya/hac-ziyaretinde-530-kisi-oldu-31-kisi-hala-kayip-845050h',
# 'https://halktv.com.tr/dunya/ingiliz-sef-jamie-oliver-ciglik-atiyor-cocuklarimizi-kurtarin-844755h',
# 'https://halktv.com.tr/dunya/sirbistanda-boya-fabrikasinda-yangin-cikti-845089h',
# 'https://halktv.com.tr/dunya/dunyaca-unlu-oyuncu-anouk-aimee-hayatini-kaybetti-844958h',
# 'https://halktv.com.tr/dunya/ulkece-karanliga-gomulduler-milyonlarca-hane-saatlerce-elektriksiz-kaldi-844926h',
# 'https://halktv.com.tr/dunya/gazzede-258-gun-can-kaybi-37-bin-431-845038h',
# 'https://halktv.com.tr/dunya/bir-ulke-daha-filistini-tanidi-845260h',
# 'https://halktv.com.tr/dunya/rusya-ukraynanin-114-ihasini-vurdu-845210h',
# 'https://halktv.com.tr/dunya/biden-netanyahuya-kizdi-toplantiyi-iptal-etti-844864h',
# 'https://halktv.com.tr/dunya/bidenin-videolari-ortaligi-karistirdi-844914h',
# 'https://halktv.com.tr/dunya/putin-guney-koreyi-uyardi-845370h',
# 'https://halktv.com.tr/dunya/aclik-oyunlarinin-yildizi-hayatini-kaybetti-845189h',
# 'https://halktv.com.tr/dunya/korkutan-sicak-hava-dalgasi-1-haftada-3-turist-olumu-844782h',
# 'https://halktv.com.tr/dunya/ilk-baski-harry-potter-kitabi-binlerce-euroya-satildi-845045h',
# 'https://halktv.com.tr/dunya/euro-bolgesinde-insaat-sektorunde-dusus-yasandi-844823h',
# 'https://halktv.com.tr/dunya/italyada-fabrikada-yangin-isciler-greve-gidiyor-845390h',
# 'https://halktv.com.tr/dunya/7-ulke-icin-disiplin-sureci-baslatilacak-844821h',
# 'https://halktv.com.tr/dunya/rusyanin-altin-ve-doviz-rezervlerinde-dusus-845285h',
# 'https://halktv.com.tr/dunya/cinin-guneyindeki-heyelanlar-can-aldi-844410h',
# 'https://halktv.com.tr/dunya/havada-facia-eski-tip-ucak-dustu-2-kisi-oldu-844196h',
# 'https://halktv.com.tr/dunya/o-sehrin-belediye-baskani-infaz-edildi-844555h',
# 'https://halktv.com.tr/dunya/iranda-deprem-olu-ve-cok-sayida-yarali-var-844658h',
# 'https://halktv.com.tr/dunya/orman-yangininda-14-bin-625-donum-kul-oldu-844225h',
# 'https://halktv.com.tr/dunya/filistinlilerin-kurban-bayrami-yangin-yerine-dondu-israil-yine-saldirdi-844686h',
# 'https://halktv.com.tr/dunya/orta-akdenizde-iki-multeci-teknesi-batti-cok-sayida-olu-ve-kayip-var-844415h',
# 'https://halktv.com.tr/dunya/tum-dunyayi-endiselendiren-sozler-3-4-ay-icinde-buyuk-bir-savas-cikacak-dedi-844172h',
# 'https://halktv.com.tr/dunya/abddeki-orman-yangini-kontrol-altina-alinamiyor-7-bin-kisi-tahliye-edilecek-844563h',
# 'https://halktv.com.tr/dunya/netanyahunun-oglu-israil-ordusunu-sucladi-844287h',
# 'https://halktv.com.tr/dunya/sirp-liderden-korkunc-savas-aciklamasi-844150h',
# 'https://halktv.com.tr/dunya/putin-24-yil-sonra-kuzey-korede-844649h',
# 'https://halktv.com.tr/dunya/gurcistanda-cifte-deprem-turkiyeden-de-hissedildi-844134h',
# 'https://halktv.com.tr/dunya/denizden-kopek-baligi-cikti-plaj-kapatildi-844460h',
# 'https://halktv.com.tr/dunya/dun-gece-neler-olmus-neler-cin-ordusundan-filipinlere-agir-yanit-844147h',
# 'https://halktv.com.tr/dunya/israilin-savas-kabinesi-dagildi-son-dakika-844167h',
# 'https://halktv.com.tr/dunya/hizbullah-israil-tankini-vurdu-844519h',
# 'https://halktv.com.tr/dunya/israilliler-netanyahu-hukumetini-protesto-etti-secimler-hemen-simdi-844391h',
# 'https://halktv.com.tr/dunya/uzayda-skandal-astronotlar-mahsur-kaldi-844262h',
# 'https://halktv.com.tr/dunya/kolombiyadaki-ogretmenlerden-eylem-egitim-ozellestirilemez-844396h',
# 'https://halktv.com.tr/dunya/abnin-rusyaya-yaptirimlari-uzatildi-844230h',
# 'https://halktv.com.tr/dunya/israil-yine-gazzedeki-nusayrat-kampini-bombardimana-tuttu-olu-ve-yaralilar-var-844401h',
# 'https://halktv.com.tr/dunya/avrupa-birligi-yaptirimlarin-suresini-uzatti-844296h',
# 'https://halktv.com.tr/dunya/mbappeden-fransa-halkina-asiri-sag-cagrisi-844195h',
# 'https://halktv.com.tr/dunya/devlet-okullarinda-sosyal-medya-da-cep-telefonlari-da-yasaklaniyor-844674h',
# 'https://halktv.com.tr/dunya/tayland-meclisi-escinsel-evliligi-onayladi-844503h',
# 'https://halktv.com.tr/dunya/cin-putinin-savasini-desteklemenin-bedelini-odemeli-844715h',
# 'https://halktv.com.tr/dunya/israil-yanlisi-unlu-yonetmen-bir-mekanda-yemek-yerken-protesto-edildi-844127h',
# 'https://halktv.com.tr/dunya/dogaya-ihanetin-fotografi-burdur-golu-cop-dagina-donusuyor-844447h',
# 'https://halktv.com.tr/dunya/karisini-oldurmek-icin-ameliyata-o-girdi-844638h',
# 'https://halktv.com.tr/dunya/israil-iha-dusurdu-844163h',
# 'https://halktv.com.tr/dunya/yunanistan-avrupa-gazzeli-cocuklara-bakmali-844691h',
# 'https://halktv.com.tr/dunya/bidendan-yarim-milyon-gocmene-vatandaslik-plani-844696h',
# 'https://halktv.com.tr/dunya/iktidar-partisi-oylarinda-dehset-erime-yuzde-19a-dustu-844137h',
# 'https://halktv.com.tr/dunya/israil-protestosunda-gazeteci-gozaltina-alindi-844641h',
# 'https://halktv.com.tr/dunya/belediye-baskani-olduruldu-844379h',
# 'https://halktv.com.tr/dunya/putin-24-yil-aradan-sonra-kuzey-koreyi-ziyarete-gidecek-844264h',
# 'https://halktv.com.tr/dunya/abdnin-gozu-orada-en-son-24-yil-once-gitmisti-putin-yeni-kartini-aciyor-844428h',
# 'https://halktv.com.tr/dunya/netanyahudan-ic-savas-tehdidi-844614h',
# 'https://halktv.com.tr/dunya/putin-kuzey-koreye-gidiyor-844285h',
# 'https://halktv.com.tr/dunya/eski-genelkurmay-baskani-evinde-olu-bulundu-844227h',
# 'https://halktv.com.tr/dunya/denizde-korku-dolu-dakikalar-2-gemi-carpisti-844204h',
# 'https://halktv.com.tr/dunya/motoru-alev-alan-yolcu-ucagi-acil-inis-yapti-844316h',
# 'https://halktv.com.tr/dunya/ekvadorda-heyelan-cok-sayida-olu-ve-kayip-var-844294h',
# 'https://halktv.com.tr/dunya/et-yiyen-bakteri-vaka-sayisi-pik-yapti-844261h',
# 'https://halktv.com.tr/dunya/israil-ordusu-gazzedeki-aclik-nedeniyle-belirli-aralar-verecek-843868h',
# 'https://halktv.com.tr/dunya/abd-baskani-biden-g-7-zirvesinde-tuhaf-davranislariyla-dikkat-cekti-iste-o-anlar-843537h',
# 'https://halktv.com.tr/dunya/prenses-kate-aylar-sonra-ilk-defa-halkin-karsisina-cikti-iste-o-anlar-843818h',
# 'https://halktv.com.tr/dunya/applea-skandal-israil-iddiasi-bagislar-israil-ordusuna-843481h',
# 'https://halktv.com.tr/dunya/meloni-bideni-beklerken-sikildi-bir-kadin-bu-kadar-bekletilmez-843379h',
# 'https://halktv.com.tr/dunya/israil-hukumetinden-ordunun-taktiksel-ara-kararina-tepki-844116h',
# 'https://halktv.com.tr/dunya/putin-rusya-ukrayna-savasinin-sonlanmasi-icin-sartlarini-sundu-843423h',
# 'https://halktv.com.tr/dunya/almanyada-iki-kiz-cocugu-20-kisilik-bir-grubun-irkci-saldirisina-ugradi-843863h',
# 'https://halktv.com.tr/dunya/morgun-sogutma-cihazi-bozulunca-sehir-korkunc-bir-kokuya-boguldu-843419h',
# 'https://halktv.com.tr/dunya/ab-duyurdu-ukrayna-ve-moldova-ile-tam-uyelik-muzakereleri-basliyor-843769h',
# 'https://halktv.com.tr/dunya/almanyada-baltali-saldirgan-panigi-844025h',
# 'https://halktv.com.tr/dunya/bakan-fidan-ukrayna-baris-zirvesine-katilacak-843494h',
# 'https://halktv.com.tr/dunya/nukleer-silahlanma-yuzde-134-artti-abd-basi-cekiyor-844119h',
# 'https://halktv.com.tr/dunya/rusyaya-yaptirim-savasi-turk-sirketleri-de-vuruyor-843321h',
# 'https://halktv.com.tr/dunya/irandan-genis-kapsamli-bayram-affi-843989h',
# 'https://halktv.com.tr/dunya/israilin-filistinli-gazetecilerin-ekipmanlarini-calmasi-kinandi-843376h',
# 'https://halktv.com.tr/dunya/alaskada-gemide-rahatsizlanan-denizci-helikopterle-tahliye-edildi-844007h',
# 'https://halktv.com.tr/dunya/evsiz-kadin-fareler-yuzunden-ayaklarini-kaybetti-843613h',
# 'https://halktv.com.tr/dunya/meloni-ve-macron-arasinda-kurtaj-tartismasi-843445h',
# 'https://halktv.com.tr/dunya/cinde-onde-gelen-metoo-aktivisti-hapis-cezasina-carptirildi-843351h',
# 'https://halktv.com.tr/dunya/isidli-tutuklular-gozalti-merkezini-ele-gecirdi-843870h',
# 'https://halktv.com.tr/dunya/hamas-abd-ile-uyum-icerisideyiz-843966h',
# 'https://halktv.com.tr/dunya/cinde-rekor-sicakliklar-tarimi-vuracak-843499h',
# 'https://halktv.com.tr/dunya/erdogan-biden-ile-gorustu-1-843478h',
# 'https://halktv.com.tr/dunya/gazzede-ateskes-saglanmazsa-bir-nesil-yok-olacak-843314h',
# 'https://halktv.com.tr/dunya/abddeki-parkta-silahli-saldiri-10-kisi-yaralandi-sayi-daha-artabilir-843916h',
# 'https://halktv.com.tr/dunya/iran-ve-isvec-arasindaki-mahkum-takasi-sonuclandi-isvec-yurttaslarina-kavustu-843895h',
# 'https://halktv.com.tr/dunya/g7-liderler-zirvesi-sonuc-bildirgesi-yayimlandi-cin-ve-iran-uyarildi-843602h',
# 'https://halktv.com.tr/dunya/alman-ekonomisi-iflaslari-durduramiyor-843360h',
# 'https://halktv.com.tr/dunya/euro-2024e-polis-kursunu-843972h',
# 'https://halktv.com.tr/dunya/peruda-6-buyuklugunde-deprem-844100h',
# 'https://halktv.com.tr/dunya/iranda-maden-ocaginda-heyelan-4-isci-gocuk-altinda-843975h',
# 'https://halktv.com.tr/dunya/rusya-turkiyeye-sinop-istegini-iletti-843625h',
# 'https://halktv.com.tr/dunya/haci-olmak-icin-mekkeye-gidenlerin-sir-olumu-nedeni-bilinmiyor-844030h',
# 'https://halktv.com.tr/dunya/ukrayna-baris-zirvesinde-putinin-ateskes-sartlari-elestirildi-843881h',
# 'https://halktv.com.tr/dunya/biden-yine-dondu-kaldi-imdadina-barack-obama-yetisti-844114h',
# 'https://halktv.com.tr/dunya/abdden-sonra-ingiltere-de-bu-sirketleri-kara-listeye-aldi-843287h',
# 'https://halktv.com.tr/dunya/almanyada-sirbistan-ingiltere-maci-oncesi-sokaklar-karisti-iste-o-anlar-844091h',
# 'https://halktv.com.tr/dunya/kuveytte-yanginda-olen-45-hindistanlinin-cenazesi-memleketlerine-goturuldu-843381h',
# 'https://halktv.com.tr/dunya/ukrayna-ordusundan-aciklama-rus-saldirisinda-14-fuzeden-7sini-dusurduk-843386h',
# 'https://halktv.com.tr/dunya/almanyada-asiri-sagci-afd-partisi-protesto-edildi-843994h',
# 'https://halktv.com.tr/dunya/kenyada-polis-hakimi-vurdu-843328h',
# 'https://halktv.com.tr/dunya/ukraynanin-guvenligine-abd-imzasi-843301h',
# 'https://halktv.com.tr/dunya/16-yasindaki-kilise-saldirganlarina-yeni-suclamalar-843374h',
# 'https://halktv.com.tr/dunya/iki-ulke-anlasti-mahkumlar-takas-edildi-843752h',
# 'https://halktv.com.tr/dunya/rodos-icin-yola-ciktilar-paralari-odediler-marmaristen-oteye-gidemediler-843999h',
# 'https://halktv.com.tr/dunya/israil-ordusu-esirlerin-tamami-askeri-operasyonla-kurtaramayiz-843860h',
# 'https://halktv.com.tr/dunya/abdden-filistine-404-milyon-dolarlik-insani-yardim-842566h',
# 'https://halktv.com.tr/dunya/rusya-ukraynada-2-yeri-daha-ele-gecirdi-842465h',
# 'https://halktv.com.tr/dunya/hizbullah-saha-komutani-oldurulunce-israile-yogun-fuze-saldirisi-baslatti-842653h',
# 'https://halktv.com.tr/dunya/bm-israil-ordusunu-kara-listeye-aldi-842596h',
# 'https://halktv.com.tr/dunya/putin-erdoganla-gorusecegi-tarihi-acikladi-842644h',
# 'https://halktv.com.tr/dunya/hizbullah-israile-gudumlu-fuze-saldirisi-duzenledi-843236h',
# 'https://halktv.com.tr/dunya/spacexin-eski-calisanlarindan-elon-muska-dava-843024h',
# 'https://halktv.com.tr/dunya/kuveytte-yangin-cok-sayida-olu-var-842699h',
# 'https://halktv.com.tr/dunya/rusyaya-kacirilan-ukraynali-cocuklar-internet-sitelerinde-tanitiliyor-842980h',
# 'https://halktv.com.tr/dunya/abnin-8-ulkesinden-ortak-ses-rus-ajanlarin-hareket-alanini-daraltmak-istiyoruz-843034h',
# 'https://halktv.com.tr/dunya/ambrey-husiler-ticaret-gemisini-vurdu-842695h',
# 'https://halktv.com.tr/dunya/ermenistan-basbakani-pasinyan-lukasenko-iktidarda-oldugu-surece-belarusa-843015h',
# 'https://halktv.com.tr/dunya/film-gibi-suikastte-kadin-kiralik-katilin-kimligi-belli-oldu-843160h',
# 'https://halktv.com.tr/dunya/rus-donanmasi-kuba-havana-limaninda-842994h',
# 'https://halktv.com.tr/dunya/kongoda-islamci-grup-42-kisiyi-oldurdu-843142h',
# 'https://halktv.com.tr/dunya/abd-buyukelcisi-turkiye-batiya-siki-sikiya-bagli-842796h',
# 'https://halktv.com.tr/dunya/kuveytteki-yangin-hintli-24-aileyi-yasa-bogdu-843103h',
# 'https://halktv.com.tr/dunya/komedyen-netanyahuyu-elestirdi-isten-kovuldu-842496h',
# 'https://halktv.com.tr/dunya/gidecek-ulke-kalmayinca-kendi-ulkesini-kurdu-843200h',
# 'https://halktv.com.tr/dunya/almanyada-fasizm-slogani-atanlara-sorusturma-baslatildi-842850h',
# 'https://halktv.com.tr/dunya/vaazlara-8-dakika-siniri-getirildi-842818h',
# 'https://halktv.com.tr/dunya/almanya-52-ulkenin-milyarlik-borclarini-sildi-843094h',
# 'https://halktv.com.tr/dunya/macron-erken-secim-ileriye-giden-tek-yol-842746h',
# 'https://halktv.com.tr/dunya/opecin-petrol-uretiminde-gunluk-29-bin-varil-artis-842484h',
# 'https://halktv.com.tr/dunya/fransanin-pop-ikonu-francoise-hardy-oldu-842722h',
# 'https://halktv.com.tr/dunya/blinken-hamas-daha-once-kabul-ettiklerini-degistirmek-istiyor-842849h',
# 'https://halktv.com.tr/dunya/biden-bir-dakika-boyunca-donup-kaldi-goruntusu-endiselendirdi-842659h',
# 'https://halktv.com.tr/dunya/fransa-cumhurbaskani-macrondan-istifa-aciklamasi-842518h',
# 'https://halktv.com.tr/dunya/petrol-rafinerisinde-yangin-cikti-843052h',
# 'https://halktv.com.tr/dunya/abden-macaristana-ceza-her-gune-1-milyon-euro-843004h',
# 'https://halktv.com.tr/dunya/israil-multeci-kampini-kusatti-842986h',
# 'https://halktv.com.tr/dunya/appledan-israile-bagis-skandali-843158h',
# 'https://halktv.com.tr/dunya/macron-neden-erken-secimlere-gidildigini-acikladi-843259h',
# 'https://halktv.com.tr/dunya/fetonun-yeni-yerini-camdaki-etiket-ortaya-cikardi-842618h',
# 'https://halktv.com.tr/dunya/rekor-sicakliklar-yunanistani-vurdu-antik-alanlar-ve-okullar-kapatildi-842820h',
# 'https://halktv.com.tr/dunya/baeli-holding-tehditler-nedeniyle-lubnanda-tv-kanali-girisiminden-vazgecti-842834h',
# 'https://halktv.com.tr/dunya/ukraynadan-kacan-siviller-avrupaya-dagildi-843070h',
# 'https://halktv.com.tr/dunya/fransiz-bakan-sagci-lidere-kritik-borc-uyarisi-842645h',
# 'https://halktv.com.tr/dunya/italya-parlamentosunda-yumruklu-kavga-milletvekili-sedye-ile-cikarildi-842960h',
# 'https://halktv.com.tr/dunya/gazzede-insani-kriz-derinlesiyor-sinirdaki-yiyecekler-curumeye-basladi-843184h',
# 'https://halktv.com.tr/dunya/brent-petrolun-varil-fiyati-8231-dolara-geriledi-842967h',
# 'https://halktv.com.tr/dunya/yeni-bir-salginla-karsi-karsiyayiz-hizla-yayilmaya-basladi-842789h',
# 'https://halktv.com.tr/dunya/erdogan-putinle-gorusecek-mi-iste-kremlin-ankara-arasinda-ilk-temas-842580h',
# 'https://halktv.com.tr/dunya/brezilya-disisleri-bakani-vieira-yarin-turkiyeye-geliyor-842503h',
# 'https://halktv.com.tr/dunya/nobel-odullu-profesor-kara-para-aklamadan-yargilaniyor-842759h',
# 'https://halktv.com.tr/dunya/klimasi-arizalanan-ucakta-yolcular-bayildi-842676h',
# 'https://halktv.com.tr/dunya/iklim-krizi-hamileleri-vurdu-843100h',
# 'https://halktv.com.tr/dunya/insan-mi-robot-mu-cinde-sergilenen-gercekci-robot-saskinlik-yaratti-842739h',
# 'https://halktv.com.tr/dunya/ingilterede-siber-saldiri-sonrasi-acil-kan-bagisi-cagrisi-841937h',
# 'https://halktv.com.tr/dunya/israil-al-jazeeranin-yasagini-45-gun-daha-uzatti-841748h',
# 'https://halktv.com.tr/dunya/hamas-abdyi-israile-baski-yapmaya-cagirdi-841969h',
# 'https://halktv.com.tr/dunya/iranda-lastik-fabrikasinda-yangin-cikti-83-isci-yaralandi-842384h',
# 'https://halktv.com.tr/dunya/fransada-siyasi-sahne-yeniden-sekilleniyor-halk-cephesi-kuruluyor-842374h',
# 'https://halktv.com.tr/dunya/sudanda-hdknin-baskin-duzenledigi-hastane-hizmet-disi-kaldi-841930h',
# 'https://halktv.com.tr/dunya/yine-polis-kursunu-19-yasindaki-genc-yasamini-yitirdi-842457h',
# 'https://halktv.com.tr/dunya/uzmanlar-uyardi-221-yilda-bir-gorulen-bocek-istilasi-basladi-841890h',
# 'https://halktv.com.tr/dunya/malavi-devlet-baskan-yardimcisi-saulos-klaus-chilimayi-ve-beraberindeki-9-kisiyi-842288h',
# 'https://halktv.com.tr/dunya/yangin-binlerce-hayvanin-canini-aldi-842308h',
# 'https://halktv.com.tr/dunya/japonyada-kurumsal-firmalar-iflasin-zirvesine-cikti-842410h',
# 'https://halktv.com.tr/dunya/221-yilda-bir-gerceklesen-bocek-istilasi-korkutuyor-842161h',
# 'https://halktv.com.tr/dunya/israil-lubnana-50-roket-atti-842412h',
# 'https://halktv.com.tr/dunya/son-dakika-avrupada-sicak-gece-fransada-secim-belcikada-istifa-841874h',
# 'https://halktv.com.tr/dunya/fransada-solcular-asiri-saga-karsi-birlesecek-842224h',
# 'https://halktv.com.tr/dunya/centcom-gazzeye-hava-operasyonuyla-10-metrik-ton-yardim-ulastirildi-841948h',
# 'https://halktv.com.tr/dunya/turbulansta-yaralananlara-25-bin-dolar-odenecek-842398h',
# 'https://halktv.com.tr/dunya/kiyiya-vuran-dev-canli-abdde-kapusonlu-gunes-baligi-kesfedildi-842026h',
# 'https://halktv.com.tr/dunya/fransadaki-ap-secimlerinde-sandiktan-asiri-sagin-cikmasi-protesto-edildi-841924h',
# 'https://halktv.com.tr/dunya/son-dakika-israil-savas-kabinesi-dagildi-bakandan-sok-istifa-841858h',
# 'https://halktv.com.tr/dunya/kuzey-korenin-balonlu-cop-hamlesine-guney-koreden-dev-misilleme-842019h',
# 'https://halktv.com.tr/dunya/bmgknin-kararina-hamastan-aciklama-842300h',
# 'https://halktv.com.tr/dunya/belcika-basbakani-istifa-edecegini-duyurdu-841921h',
# 'https://halktv.com.tr/dunya/hindistanda-otobuse-silahli-saldiri-duzenlendi-10-olu-33-yarali-842056h',
# 'https://halktv.com.tr/dunya/savas-ucagi-yere-cakildi-2-pilot-hayatini-kaybetti-842318h',
# 'https://halktv.com.tr/dunya/ap-secim-sonuclari-parlamento-saga-mi-kaydi-841947h',
# 'https://halktv.com.tr/dunya/abd-disisleri-bakani-israil-muhalefet-liderleri-ile-gorustu-842380h',
# 'https://halktv.com.tr/dunya/hamas-ateskese-olumlu-bakiyoruz-demisti-abd-ateskesi-hamas-kabul-etmiyor-842156h',
# 'https://halktv.com.tr/dunya/iranda-ahmedinejada-bir-veto-daha-aday-listesindeki-6-isim-belli-oldu-841797h',
# 'https://halktv.com.tr/dunya/abd-disisleri-bakani-blinkenden-ortadoguda-kritik-gorusmeler-842113h',
# 'https://halktv.com.tr/dunya/ukrayna-baris-konferansina-turkiyede-gidiyor-842183h',
# 'https://halktv.com.tr/dunya/gazze-ateskes-tasarisi-icin-disislerinden-ilk-aciklama-842274h',
# 'https://halktv.com.tr/dunya/cecenistan-sinir-koyunu-ele-gecirdik-ukrayna-yalanladi-841994h',
# 'https://halktv.com.tr/dunya/abdli-4-akademisyen-cinde-bicakli-saldiriya-ugradi-842317h',
# 'https://halktv.com.tr/dunya/macron-fransiz-meclisini-feshetti-841863h',
# 'https://halktv.com.tr/dunya/israilde-savas-kabinesi-krizi-gantz-istifa-etti-842087h',
# 'https://halktv.com.tr/dunya/israil-deyr-el-belahdan-katliamla-cekildi-842029h',
# 'https://halktv.com.tr/dunya/iranda-cumhurbaskani-adaylari-netlesti-841767h',
# 'https://halktv.com.tr/dunya/lav-izlandadaki-yolu-yuttu-841815h',
# 'https://halktv.com.tr/dunya/ingilterede-issizlik-son-25-yilin-en-yuksek-seviyesini-gordu-842455h',
# 'https://halktv.com.tr/dunya/luks-mucevher-magazasi-soyuldu-841806h',
# 'https://halktv.com.tr/dunya/guney-kore-ile-kuzey-kore-arasinda-gerilim-yukseliyor-842287h',
# 'https://halktv.com.tr/dunya/prenses-kate-middleton-sessizligini-bozdu-842099h',
# 'https://halktv.com.tr/dunya/umuda-giden-yol-yemen-sularinda-son-buldu-38-kisi-oldu-842341h',
# 'https://halktv.com.tr/dunya/rusya-baskani-putin-hakan-fidan-ile-gorusecek-842388h',
# 'https://halktv.com.tr/dunya/sahildeki-kabus-kopekbaligi-3-kisiyi-yaraladi-842005h',
# 'https://halktv.com.tr/dunya/skandal-aciklama-abd-israili-tebrik-etti-841605h',
# 'https://halktv.com.tr/dunya/putinden-turk-ekonomisi-icin-erdogana-uyari-tehlikeye-girebilir-841580h',
# 'https://halktv.com.tr/dunya/danimarka-basbakani-saldiriya-ugradi-841345h',
# 'https://halktv.com.tr/dunya/yuksek-sesli-muzige-kizan-komsu-baba-ve-oglunu-gozunu-kirpmadan-oldurdu-841487h',
# 'https://halktv.com.tr/dunya/biden-zelenskiyden-ozur-diledi-841278h',
# 'https://halktv.com.tr/dunya/dusen-dogum-oranlarina-karsi-flort-uygulamasi-basliyor-840921h',
# 'https://halktv.com.tr/dunya/gazzede-katliamin-bilancosu-yikim-kitlik-ve-katliam-841128h',
# 'https://halktv.com.tr/dunya/chpli-vekil-faik-oztrak-nato-pa-baskan-yardimciligi-gorevini-yurutecek-841170h',
# 'https://halktv.com.tr/dunya/yer-yerinden-oynayacak-erdogan-putin-ile-hangi-sartlarda-anlasti-remzi-ozdemirden-840952h',
# 'https://halktv.com.tr/dunya/imran-hanin-hapishane-fotograflari-sizdirildi-turkiye-detayi-tam-anlamiyla-bomba-841306h',
# 'https://halktv.com.tr/dunya/abdnin-en-yuksek-mahkemesinin-yargiclari-finansal-beyanlarini-acikladi-841440h',
# 'https://halktv.com.tr/dunya/cinde-en-zorlu-sinavina-rekor-katilim-13-milyon-ogrenci-yaristi-841077h',
# 'https://halktv.com.tr/dunya/israil-gece-boyu-gazzeye-saldirdi-cok-sayida-olu-ve-yarali-var-841647h',
# 'https://halktv.com.tr/dunya/kadikoy-belediyesi-israil-sehriyle-yapilan-kardes-sehir-protokolunu-sonlandirdi-841265h',
# 'https://halktv.com.tr/dunya/el-nusayrat-multeci-kampinda-274-sivil-oldu-841693h',
# 'https://halktv.com.tr/dunya/rusya-ukrayna-sivil-olumlerinde-abdyi-sucluyor-841167h',
# 'https://halktv.com.tr/dunya/himalayalardaki-uc-zirveden-cop-ceset-ve-iskelet-cikarildi-841120h',
# 'https://halktv.com.tr/dunya/unlu-sosis-markasinda-salmonella-bakterisi-bulundu-marketlerden-toplatiliyor-841273h',
# 'https://halktv.com.tr/dunya/cindeki-kesintisiz-selaleye-borudan-su-verildigi-ortaya-cikti-841066h',
# 'https://halktv.com.tr/dunya/abde-secim-maratonunda-sona-gelindi-841623h',
# 'https://halktv.com.tr/dunya/nato-genel-sekreteri-stoltenberg-ukrayna-rusyadaki-hedefleri-vurma-hakkina-sahip-841216h',
# 'https://halktv.com.tr/dunya/iki-ulke-arasinda-cop-balonu-savasi-841600h',
# 'https://halktv.com.tr/dunya/ingiliz-tv-sunucusu-mosley-gunlerdir-kayipti-olu-bulundu-841680h',
# 'https://halktv.com.tr/dunya/dehset-veren-baskin-silahli-saldirganlar-koyu-katletti-180-kadin-ve-cocuk-841020h',
# 'https://halktv.com.tr/dunya/putin-bati-para-birimlerinin-kullanimini-azaltiyoruz-841240h',
# 'https://halktv.com.tr/dunya/biden-israile-destegi-yuzunden-partisinden-500-bin-oy-kaybetti-841292h',
# 'https://halktv.com.tr/dunya/avrupa-komisyonu-baskan-yardimcisi-katliam-derhal-sona-ermelidir-841670h',
# 'https://halktv.com.tr/dunya/abd-baskani-biden-olmayan-sandalyeye-oturmaya-calisti-840940h',
# 'https://halktv.com.tr/dunya/erdogana-soguk-dus-rusyadan-geldi-putin-turkiyeyi-acik-acik-tehdit-etti-840917h',
# 'https://halktv.com.tr/dunya/yunan-emniyeti-ayakta-bbc-sunucusu-bulunamiyor-841171h',
# 'https://halktv.com.tr/dunya/haitinin-yeni-basbakani-apar-topar-hastaneye-kaldirildi-841695h',
# 'https://halktv.com.tr/dunya/bakan-fidan-hamas-lideri-ile-gorustu-841686h',
# 'https://halktv.com.tr/dunya/arnavutlukta-hukumet-istifa-protestosu-840947h',
# 'https://halktv.com.tr/dunya/otelde-bomba-yapmaya-calisirken-yakalandi-840868h',
# 'https://halktv.com.tr/dunya/yandang-daginda-dagcilar-mahsur-kaldi-kalabalik-endise-yaratti-841105h',
# 'https://halktv.com.tr/dunya/film-degil-gercek-5-metrelik-piton-bir-kisiyi-yuttu-841727h',
# 'https://halktv.com.tr/dunya/disisleri-israilin-multeci-kampina-saldirisini-lanetliyoruz-841666h',
# 'https://halktv.com.tr/dunya/netanyahu-kongre-davetini-kabul-etti-hakli-savasimizi-duyuracagim-841063h',
# 'https://halktv.com.tr/dunya/rusyada-acil-durum-ilani-841297h',
# 'https://halktv.com.tr/dunya/termometreler-50-dereceyi-gordu-adinin-hakkini-verdi-orasi-artik-dunyadaki-841451h',
# 'https://halktv.com.tr/dunya/abd-disisleri-bakani-blinken-gazze-icin-ortadoguya-gidiyor-841431h',
# 'https://halktv.com.tr/dunya/abd-baskani-biden-zelenskiden-ozur-diledi-841309h',
# 'https://halktv.com.tr/dunya/17-ulkeden-hamasa-cagri-kaybedecek-zaman-yok-840898h',
# 'https://halktv.com.tr/dunya/israilin-filistindeki-siddeti-devam-ediyor-210-olu-400-yarali-841569h',
# 'https://halktv.com.tr/dunya/hisse-senetlerindeki-artis-zenginleri-tarihin-en-zenginleri-yapiyor-840885h',
# 'https://halktv.com.tr/dunya/hakan-fidan-rusyaya-gidiyor-1-841742h',

        ]
        all_data = set()
        for index, site in enumerate(siteler):
            first_site = (index == 0)  # Sadece ilk site için çerez kabul etme işlemi yapılacak
            site_data = self.collect_data_from_site(site, first_site)
            all_data.update(site_data)

        self.save_data_to_json(all_data)

if __name__ == "__main__":
    from seleniumbase import get_test_methods
    with SB(uc_cdp=True, guest_mode=True) as driver:
        get_test_methods(WebScraper)
